config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :brands, only: :create
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'others' => 'posts#others'
  resources :nominees do
    get 'posts', to: 'posts#search'
  end
  resources :users do
    resources :jeans
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  get 'my_page' => 'users#my_page'
  get 'my_page/edit' => 'users#edit'
  get 'my_page/jeans' => 'jeans#index'
  get 'my_page/jeans/:id' => 'jeans#show', as: 'my_jeans'
  get 'my_page/timeline' => 'posts#timeline', as: 'timeline'
  get 'this_week', to: 'nominees#this_week'
  get 'last_weeks_winner', to: 'nominees#last_weeks_winner'
  resources :tags do
    get 'posts', to: 'posts#search'
  end
  resources :nominee_maps, only: [:create, :destroy]

end

app/models/award.rb
class Award < ApplicationRecord

  has_many :award_maps, dependent: :destroy, foreign_key: 'award_id'
  has_many :jeans, through: :award_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/award_map.rb
class AwardMap < ApplicationRecord

  belongs_to :jeans, optional: true
  belongs_to :award, optional: true

  enum award_id: { "Best Faded": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :lots
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  belongs_to :parent,  class_name: "Comment", optional: true
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/jeans.rb
class Jeans < ApplicationRecord

  belongs_to :lot, optional: true
  belongs_to :brand, optional: true
  belongs_to :year, optional: true
  belongs_to :user, optional: true
  has_many :posts
  has_many :nominee_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :nominees, through: :nominee_maps
  has_many :award_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :awards, through: :award_maps

  mount_uploader :jeans_image, JeansUploader

  def is_nominated_by?(jeans, user)
    jeans.nominee_maps.find_by(user_id: user.id)
  end
end

app/models/lot.rb
class Lot < ApplicationRecord
  belongs_to :brand, optional: true
  has_many :years
end

app/models/nominee.rb
class Nominee < ApplicationRecord

  has_many :nominee_maps, dependent: :destroy, foreign_key: 'nominee_id'
  has_many :jeans, through: :nominee_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5}  # whisker ポケット下からモモの上まで , shevron モモから下の部分
end

app/models/nominee_map.rb
class NomineeMap < ApplicationRecord

  belongs_to :nominee,  optional: true
  belongs_to :jeans,  optional: true

  enum nominee_id: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :jean, optional: true
  belongs_to :user, optional: true


  mount_uploader :image, PostUploader

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags # 現在取得した@postに存在するタグから、送信されてきたタグを除いたタグをold_tagsとする。
    new_tags = sent_tags - current_tags # 送信されてきたタグ(sent_tag)から、現在存在するタグを除いたタグをnew_tagsとする。

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new) # tag_nameが存在していなければ、新たにレコード追加、既に存在する場合は既存のレコードを取得
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :post, optional: true

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jeans, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  mount_uploader :image, ImageUploader


  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :lot, optional: true
end

app/controllers/jeans_controller.rb
class JeansController < ApplicationController

  def index
    @jeans = Jeans.new
    @user_jeans = current_user.jeans.order(id: :desc)
    @today = Date.today
  end

  def create
    jean = Jeans.new(jeans_params)
    jean.save
    redirect_to request.referer
  end

  def show
    @jeans = Jeans.find(params[:id])
    @today = Date.today
  end

  def update
    @jeans = Jeans.find(params[:id])
    @jeans.update(jeans_params)
    redirect_to request.referer
  end

  private
    def jeans_params
       params.require(:jeans).permit(:name, :user_id, :brand_id, :lot_id, :year_id, :number_of_laundry, :date_of_purchase, :jeans_image) # 変更後
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jeans_helper.rb
module JeansHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jeans/_form.html.haml
= bootstrap_form_with(model:[current_user, jeans], local: true) do |f|
  .form_group
    -if jeans.jeans_image.url
      = image_tag jeans.jeans_image.url, id: :img_prev, size: "200x230", class: "shadow-lg p-3 mb-5 bg-white rounded"
    -else
      = image_tag 'no_jeans.jpg', id: :img_prev, size: "200x230", class: "shadow-lg p-3 mb-5 bg-white rounded"
  .form_group
    = f.text_field :name, :placeholder => "Give your jeans specify name"
  .file_form_group
    = f.file_field :jeans_image, {class: "file_field_message", id: "user_img"}
  .form-group
    = f.collection_select :brand_id, Brand.all, :id, :name, {include_blank: "Select jeans brand", prompt: false}
  .form-group
    // 中カテゴリが差し込ませるポイントを指定するために追加
    #medium_category_insert_point
    // EDIT時、中カテゴリーのダミー表示の切替
    #medium_category
      - if jeans.lot_id.blank?
        = f.select :lot_id, [], include_blank: "---"
      -else
        = f.collection_select :lot_id, jeans.brand.lots, :id, :number, {include_blank: "---", prompt: false }
    // 小カテゴリが差し込ませるポイントを指定するために追加
    #small_category_insert_point

    // EDIT時、小カテゴリのダミー表示の切替
    #small_category
      - if jeans.year_id.blank?
        = f.select :year_id, [], include_blank: "---"
      - else
        = f.collection_select :year_id, jeans.lot.years, :id, :date_of_birth, {include_blank: "---", prompt: false }
    // 中カテゴリのtamplateを作成
    - Brand.all.each do |brand|
      // このidをもとに呼び出される(コメントもインデント揃える)
      %template{id: "medium_category#{brand.id}"}
        #selected_medium_category
          = f.collection_select :lot_id, brand.lots, :id, :number, {include_blank: "Select Jeans Lot", prompt: false}

      // 中カテゴリのtamplate作成途中に、小カテゴリのtamplateを作成を挟む
      - brand.lots.each do |lot|
        %template{id: "small_category#{lot.id}"}
          #selected_small_category

            = f.collection_select :year_id, lot.years, :id, :date_of_birth, {include_blank: "Select Jeans Model", prompt: false}

  .form-group
    %p ◆ When did you purchase?
    = f.date_field :date_of_purchase, {class: "form-control text-gray"}
    = f.hidden_field :user_id, value: current_user.id
  .form-group
    %p ◆ How many times did you rinse your jeans?
    = f.select :number_of_laundry, options_for_select((0..500).to_a), {prompt: "Select number"}, {class: "selectpicker"}
    = f.submit  class: "btn btn-primary"

app/views/jeans/edit.html.haml
.container
  .row.mx-auto
    %h1.col-12.mb-5 Register your jeans
    = render "form", jeans: @jeans

app/views/jeans/index.html.haml
.container
  .row.mx-auto
    .col-6
      %h3.mb-5
        Your Jeans
      - @user_jeans.each do |j|
        %ul.list-unstyled
          %li.d-flex
            = link_to my_jeans_path(j) do
              = image_tag j.jeans_image.url, size: "200x230", class: "ml-auto shadow-lg mb-5 bg-white rounded"
            .flex-column.p-4
              %strong
                = j.name
              .mb-3
                = j.brand.name
                = j.lot.number if j.lot_id.present?
                = j.year.date_of_birth if j.year_id.present?
              - date =  (@today - j.date_of_purchase).to_i
              .small
                ・You have been wearing this for
                %span.font-weight-bold
                  #{date}
                days!
              .small
                ・You washed this
                %span.font-weight-bold
                  #{j.number_of_laundry}
                times!
    .col-5
      %h3.mb-5 Register your jeans
      = render "jeans/form", jeans: @jeans

app/views/jeans/show.html.haml
.container
  .row.mx-auto
    .col-6
      = image_tag @jeans.jeans_image.url, size: "400x430", class: "shadow-lg p-3 mb-5 bg-white rounded"
      .flex-column.font-weight-bold.mb-3.mt-3
        = @jeans.brand.name
        = @jeans.lot.number if @jeans.lot_id.present?
        = @jeans.year.date_of_birth if @jeans.year_id.present?
      - date =  (@today - @jeans.date_of_purchase).to_i
      .small
        ・You have been wearing this for
        %span.font-weight-bold
          #{date}
        days!
      .small
        ・You washed this
        %span.font-weight-bold
          #{@jeans.number_of_laundry}
        times!

    .col-5
      %h3.mb-5 Edit your jeans
      = render "jeans/form", jeans: @jeans