config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :brands, only: :create
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'others' => 'posts#others'
  resources :nominees do
    get 'posts', to: 'posts#search'
  end
  resources :users do
    resources :jeans
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  get 'my_page' => 'users#my_page'
  get 'my_page/edit' => 'users#edit'
  get 'my_page/jeans' => 'jeans#index'
  get 'my_page/jeans/:id' => 'jeans#show', as: 'my_jeans'
  get 'my_page/timeline' => 'posts#timeline', as: 'timeline'
  get 'this_week', to: 'nominees#this_week'
  get 'last_weeks_winner', to: 'nominees#last_weeks_winner'
  resources :tags do
    get 'posts', to: 'posts#search'
  end
  resources :nominee_maps, only: [:create, :destroy]

end

app/models/award.rb
class Award < ApplicationRecord

  has_many :award_maps, dependent: :destroy, foreign_key: 'award_id'
  has_many :jeans, through: :award_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/award_map.rb
class AwardMap < ApplicationRecord

  belongs_to :jeans, optional: true
  belongs_to :award, optional: true

  enum award_id: { "Best Faded": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :lots
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  belongs_to :parent,  class_name: "Comment", optional: true
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/jeans.rb
class Jeans < ApplicationRecord

  belongs_to :lot, optional: true
  belongs_to :brand, optional: true
  belongs_to :year, optional: true
  belongs_to :user, optional: true
  has_many :posts
  has_many :nominee_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :nominees, through: :nominee_maps
  has_many :award_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :awards, through: :award_maps

  mount_uploader :jeans_image, JeansUploader

  def is_nominated_by?(jeans, user)
    jeans.nominee_maps.find_by(user_id: user.id)
  end
end

app/models/lot.rb
class Lot < ApplicationRecord
  belongs_to :brand, optional: true
  has_many :years
end

app/models/nominee.rb
class Nominee < ApplicationRecord

  has_many :nominee_maps, dependent: :destroy, foreign_key: 'nominee_id'
  has_many :jeans, through: :nominee_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5}  # whisker ポケット下からモモの上まで , shevron モモから下の部分
end

app/models/nominee_map.rb
class NomineeMap < ApplicationRecord

  belongs_to :nominee,  optional: true
  belongs_to :jeans,  optional: true

  enum nominee_id: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :jean, optional: true
  belongs_to :user, optional: true


  mount_uploader :image, PostUploader

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags # 現在取得した@postに存在するタグから、送信されてきたタグを除いたタグをold_tagsとする。
    new_tags = sent_tags - current_tags # 送信されてきたタグ(sent_tag)から、現在存在するタグを除いたタグをnew_tagsとする。

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new) # tag_nameが存在していなければ、新たにレコード追加、既に存在する場合は既存のレコードを取得
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :post, optional: true

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jeans, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  mount_uploader :image, ImageUploader


  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :lot, optional: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def my_page
    @user = current_user
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to my_page_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :introduction, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jeans_helper.rb
module JeansHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.container
  .row
    .col-6.mx-auto
      %h2
        Edit Your Profile
      = bootstrap_form_with(model: current_user, url: user_path(current_user), local: true) do |f|
        -if current_user.image.url
          .user_image.text-center.p-3
            = image_tag current_user.image.url, size: "200x200", id: :img_prev, class: "text-center shadow mb-5 bg-white rounded-circle"
        -else
          = image_tag 'no_jeans.jpg', id: :img_prev, size: "200x230", class: "shadow mb-5 bg-white rounded-circle"
        = f.file_field :image, {class: "file_field_message", id: "user_img"}
        = f.text_field :name
        = f.text_area :introduction
        = f.submit

app/views/users/my_page.html.haml
.container
  .row.mx-auto
    .col-6
      %h2.mb-5
        Your Profile
      .flex-column
        .ml_auto.mb-2
          -if current_user.image.url
            = image_tag current_user.image.url, size: "300x300", class: "shadow mb-5 bg-white rounded-circle"
          -else
            = image_tag 'no_jeans.jpg', size: "90x90", class: "shadow mb-5 bg-white rounded-circle"
        .ml_auto.font-weight-bold.mb-1
          = current_user.name
        .ml-auto
          = current_user.introduction
        .d-flex.p-2
          %p
            Posts
            %strong
              = current_user.posts.count
            | Follower
            %strong
              = current_user.followers.count
            | Following
            %strong
              = current_user.followings.count
        = link_to my_page_jeans_path do
          %strong view your jeans
        %br
          = link_to my_page_edit_path do
            %strong edit your profile

    .col-6
      %h2.mb-5
        Records of Award
      .d-flex.p-2.flex-column
        .d-flex.p-2
          %i.fas.fa-award.award_icons
          %h5.faded_award_font.ml-3.d-flex.align-items-center
            Best Faded Award
        - user_jeans = @user.jeans.where('number_of_award > 0')
        - if user_jeans.present?
          %table.table.table-dark.small.m-4
            %thead
              %tr
                %th{scope: "col"}
                  Jeans Image
                %th{scope: "col"}
                  Jeans Name
                %th{scope: "col"}
                  Time of Award
            %tbody
              - user_jeans.each do |award_jeans|
                - award_jeans.award_maps.order(created_at: "desc").each do |award_jean|
                  - if award_jean.award_id == "Best Faded"
                    %tr
                      %td{scope: "row"}
                        = image_tag award_jeans.jeans_image.url, size: "40x40", class: "rounded-circle"
                      %td
                        = award_jeans.name
                      %td
                        = award_map.created_at.strftime("%Y-%m-%d-%a")

        .d-flex.p-2
          %i.fas.fa-award.award_icons
          %h5.fashionable_award_font.ml-3.d-flex.align-items-center
            Best Fashinable Award
        - user_jeans = @user.jeans.where('number_of_award > 0')
        - if user_jeans.present?
          %table.table.table-dark.small.m-4
            %thead
              %tr
                %th{scope: "col"}
                  Jeans Image
                %th{scope: "col"}
                  Jeans Name
                %th{scope: "col"}
                  Time of Award
            %tbody
              - user_jeans.each do |award_jeans|
                - award_jeans.award_maps.order(created_at: "desc").each do |award_map|
                  - if award_map.award_id == "Best Fashionable"
                    %tr
                      %td{scope: "row"}
                        = image_tag award_jeans.jeans_image.url,size: "40x40", class: "rounded-circle"
                      %td
                        = award_jeans.name
                      %td
                        = award_map.created_at.strftime("%Y-%m-%d-%a")

        .d-flex.p-2
          %i.fas.fa-award.award_icons
          %h5.whisker_award_font.ml-3.d-flex.align-items-center
            Best Whisker Award
        - user_jeans = @user.jeans.where('number_of_award > 0')
        - if user_jeans.present?
          %table.table.table-dark.small.m-4
            %thead
              %tr
                %th{scope: "col"}
                  Jeans Image
                %th{scope: "col"}
                  Jeans Name
                %th{scope: "col"}
                  Time of Award
            %tbody
              - user_jeans.each do |award_jeans|
                - award_jeans.award_maps.order(created_at: "desc").each do |award_map|
                  - if award_map.award_id == "Best Whisker"
                    %tr
                      %td{scope: "row"}
                        = image_tag award_jeans.jeans_image.url,size: "40x40", class: "rounded-circle"
                      %td
                        = award_jeans.name
                      %td
                        = award_map.created_at.strftime("%Y-%m-%d-%a")

        .d-flex.p-2
          %i.fas.fa-award.award_icons
          %h5.shevron_award_font.ml-3.d-flex.align-items-center
            Best Shevron Award
        - user_jeans = @user.jeans.where('number_of_award > 0')
        - if user_jeans.present?
          %table.table.table-dark.small.m-4
            %thead
              %tr
                %th{scope: "col"}
                  Jeans Image
                %th{scope: "col"}
                  Jeans Name
                %th{scope: "col"}
                  Time of Award
            %tbody
              - user_jeans.each do |award_jeans|
                - award_jeans.award_maps.order(created_at: "desc").each do |award_map|
                  - if award_map.award_id == "Best Shevron"
                    %tr
                      %td{scope: "row"}
                        = image_tag award_jeans.jeans_image.url,size: "40x40", class: "rounded-circle"
                      %td
                        = award_jeans.name
                      %td
                        = award_map.created_at.strftime("%Y-%m-%d-%a")

        .d-flex.p-2
          %i.fas.fa-award.award_icons
          %h5.best_501_award_font.ml-3.d-flex.align-items-center
            Best 501 Award
        - user_jeans = @user.jeans.where('number_of_award > 0')
        - if user_jeans.present?
          %table.table.table-dark.small.m-4
            %thead
              %tr
                %th{scope: "col"}
                  Jeans Image
                %th{scope: "col"}
                  Jeans Name
                %th{scope: "col"}
                  Time of Award
            %tbody
              - user_jeans.each do |award_jeans|
                - award_jeans.award_maps.order(created_at: "desc").each do |award_map|
                  - if award_map.award_id == "Best 501"
                    %tr
                      %td{scope: "row"}
                        = image_tag award_jeans.jeans_image.url,size: "40x40", class: "rounded-circle"
                      %td
                        = award_jeans.name
                      %td
                        = award_map.created_at.strftime("%Y-%m-%d-%a")

app/views/users/show.html.haml
.container-fluid
  .row
    = render 'layouts/sidebar'
    .col-6.mx-auto
      %h2.mb-5
        User Profile
      .d-flex
        .ml_auto.mb-2
          -if @user.image.url
            = image_tag @user.image.url, size: "70x70", class: "shadow mb-5 bg-white rounded-circle"
          -else
            = image_tag 'no_jeans.jpg', size: "70x70", class: "shadow mb-5 bg-white rounded-circle"
        .flex-column.ml-4
          .ml_auto.font-weight-bold.mb-1
            = @user.name
          .ml-auto
            = @user.introduction
          .d-flex
            %p
              Posts
              %strong
                = @user.posts.count
              | Follower
              %strong
                = @user.followers.count
              | Following
              %strong
                = @user.followings.count
          .d-flex.icons
            - if @user != current_user
              - if @user.is_followed_by?(current_user)
                = link_to user_relationships_path(user_id: @user.id), method: :delete do
                  %button.btn.btn-danger
                    Unfollow #{@user.name}
              - else
                = link_to user_relationships_path(user_id: @user.id), method: :post do
                  %button.btn.btn-primary
                    Follow #{@user.name}
          .d-flex
            -if @user == current_user
              = link_to my_page_jeans_path do
                %strong view your jeans

      - @user.posts.each do |post|
        - comment = post.comments.build
        - comment_reply = post.comments.build
        - comments = Comment.includes(:user).where(post_id: post.id).order(created_at: :desc)
        = render 'posts/posts', {post: post, comment: comment, comment_reply: comment_reply, comments: comments }

    .col-3