config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :brands, only: :create
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'others' => 'posts#others'
  resources :nominees do
    get 'posts', to: 'posts#search'
  end
  resources :users do
    resources :jeans
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  get 'my_page' => 'users#my_page'
  get 'my_page/edit' => 'users#edit'
  get 'my_page/jeans' => 'jeans#index'
  get 'my_page/jeans/:id' => 'jeans#show', as: 'my_jeans'
  get 'my_page/timeline' => 'posts#timeline', as: 'timeline'
  get 'this_week', to: 'nominees#this_week'
  get 'last_weeks_winner', to: 'nominees#last_weeks_winner'
  resources :tags do
    get 'posts', to: 'posts#search'
  end
  resources :nominee_maps, only: [:create, :destroy]

end

app/models/award.rb
class Award < ApplicationRecord

  has_many :award_maps, dependent: :destroy, foreign_key: 'award_id'
  has_many :jeans, through: :award_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/award_map.rb
class AwardMap < ApplicationRecord

  belongs_to :jeans, optional: true
  belongs_to :award, optional: true

  enum award_id: { "Best Faded": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :lots
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  belongs_to :parent,  class_name: "Comment", optional: true
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/jeans.rb
class Jeans < ApplicationRecord

  belongs_to :lot, optional: true
  belongs_to :brand, optional: true
  belongs_to :year, optional: true
  belongs_to :user, optional: true
  has_many :posts
  has_many :nominee_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :nominees, through: :nominee_maps
  has_many :award_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :awards, through: :award_maps

  mount_uploader :jeans_image, JeansUploader

  def is_nominated_by?(jeans, user)
    jeans.nominee_maps.find_by(user_id: user.id)
  end
end

app/models/lot.rb
class Lot < ApplicationRecord
  belongs_to :brand, optional: true
  has_many :years
end

app/models/nominee.rb
class Nominee < ApplicationRecord

  has_many :nominee_maps, dependent: :destroy, foreign_key: 'nominee_id'
  has_many :jeans, through: :nominee_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5}  # whisker ポケット下からモモの上まで , shevron モモから下の部分
end

app/models/nominee_map.rb
class NomineeMap < ApplicationRecord

  belongs_to :nominee,  optional: true
  belongs_to :jeans,  optional: true

  enum nominee_id: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :jean, optional: true
  belongs_to :user, optional: true


  mount_uploader :image, PostUploader

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags # 現在取得した@postに存在するタグから、送信されてきたタグを除いたタグをold_tagsとする。
    new_tags = sent_tags - current_tags # 送信されてきたタグ(sent_tag)から、現在存在するタグを除いたタグをnew_tagsとする。

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new) # tag_nameが存在していなければ、新たにレコード追加、既に存在する場合は既存のレコードを取得
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :post, optional: true

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jeans, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  mount_uploader :image, ImageUploader


  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :lot, optional: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:others]

  def others
    if user_signed_in?
      @posts = Post.all
      from  = Time.current.at_beginning_of_day
      to    = (from - 6.day).at_end_of_day
      @winners = AwardMap.where(created_at: to...from)
    else
      @posts = Post.all.shuffle
      # 一週間分のレコードを取得
      from  = Time.current.at_beginning_of_day
      to    = (from - 6.day).at_end_of_day
      @winners = AwardMap.where(created_at: to...from)  # ...でfrom 以上 to 未満
    end
  end

  def index
    @user_jeans = current_user.jeans
    @users = User.where.not(id: current_user.id)
    @posts = current_user.posts.order(created_at: :desc)
    @tag_list = Tag.all
  end


  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build  # 投稿全体へのコメント投稿用の変数
    @comment_reply = @post.comments.build  # コメントに対する返信用の変数
    @comments = Comment.includes(:user).where(post_id: @post.id).order(created_at: :desc)
    post_jeans = Jeans.find_by(id: @post.jeans_id)
    date =  (@post.created_at - post_jeans.date_of_purchase.to_time.to_datetime).to_i
    @difference_date = (date / 1.day)
  end

  def create
    @post = current_user.posts.new(post_params)
    tag_list = params[:post][:tag_name].split(nil)
    if @post.save
      @post.save_tag(tag_list)
      redirect_to request.referer
    else
      render request.referer
    end
  end

   def timeline
      @posts_all = Post.all
      @user = current_user
      @follow_users = @user.followings  # ユーザーのフォローする他ユーザーの投稿を持ってくる
      @posts = @posts_all.where(user_id: @follow_users).order("created_at DESC")
   end



  private
   def post_params
     params.require(:post).permit(:image, :body, :jeans_id)
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jeans_helper.rb
module JeansHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_posts.html.haml
.row
  .col-10.pr-0{id: "flash_#{post.id}"}
    .card.mb-4.mt-5
      .bd-placeholder-img.card-img-top
        = link_to post_path(post) do
          = image_tag post.image.url, class: "card-image", id: "flash_#{post.id}"
      .card-body
        - post_jeans = Jeans.find_by(id: post.jeans_id)
        .d-flex
          = link_to user_path(post.user) do
            = image_tag post.user.image.url, size: "50x50", class: "rounded-circle"
          .flex-column.ml-3
            %strong
              #{post_jeans.name}
            %p.small
              #{post_jeans.brand.name} #{post_jeans.lot.number} #{post_jeans.year.date_of_birth}
        %p.card-text
          = post.body
        %p.text-right.small
          = post.created_at.strftime("%Y-%m-%d %H:%M")
        .d-flex
          - post.tags.each do |tag|
            %p.card.rounded-pill.p-2.mr-2.small
              = link_to tag_path(tag), class: "link edit-icon" do
                = tag.tag_name
        .d-flex.icons
          -if post_jeans.is_nominated_by?(post_jeans, current_user)
            .position-relative.mr-3
              %i.fas.fa-check-circle.mr-4.trophy_complete{onClick: "click_trophy_complete()"}
          -else
            .position-relative.mr-3
              %i.fas.fa-trophy.text-warning.mr-4.trophy_icon{onClick: "click_trophy_icon(this)", id: "#{post.id}" }
          .div{id: "post_#{post.id}"}
            .favorite_btn
              = render "favorites/favorite_btn", post: post
          .div{id: "relationship_#{post.id}"}
            .relationship_btn
              = render "relationships/relationship_btn", post: post
          .ml-5
            = social_share_button_tag( post.body)
      .nominate_form.ml-3.mb-3.mr-3.pt-3.border-top{id: "nominate_form_#{post.id}"}
        = bootstrap_form_with url: nominee_maps_path, local: true do |f|
          .mb-2
            Nominate This Jeans to...
          .d-flex
            = f.select :nominee_id, NomineeMap.nominee_ids.keys, hide_label: true
            = f.hidden_field :jeans_id, value: post.jeans_id
            = f.hidden_field :user_id, value: current_user.id
          = f.submit 'Vote!', class: "btn btn-primary"
          .nominate_close_button.btn.btn-dark{onclick: "close_trophy_icon(this)", id: "#{post.id}"}
            Close
      // .comments_index
      //   .div{id: "comments_and_form_#{post.id}"}
      //     = render "comments/index", {comment: comment, comments: comments, comment_reply: comment_reply, post: post}
  //サイドバー　背景とに日にち設定
  - post_jeans = Jeans.find_by(id: post.jeans_id)
  - date =  (post.created_at - post_jeans.date_of_purchase.to_time.to_datetime).to_i
  - difference_date = (date / 1.day)
  -if difference_date < 10
    .col-2.first_step.mb-4.mt-5.border-right.border-top
      %p.strong.h4.text-white.pt-3
        Day
        = difference_date
  - elsif difference_date > 10
    .col-2.second_step.mb-4.mt-5.border-right.border-top
      %p.strong.h4.text-white.pt-3
        Day
        = difference_date
  -elsif difference_date > 60
    .col-2.third_step.mb-4.mt-5.border-right.border-top
      %p.strong.h4.text-white.pt-3
        Day
        = difference_date

app/views/posts/index.html.haml
.container-fluid
  .row
    = render 'layouts/sidebar'
    .col-6.mx-auto
      .w-75
        %h2
          .mb-4
            Post Your Jeans
        = bootstrap_form_with(url: posts_path, model: Post.new, local: true) do |f|
          .form_group
            = f.file_field :image, {class: "file_field_message", id: "user_img"}
          .form-group
            = f.text_area :body
          .form_group
            = f.select :jeans_id, @user_jeans.collect { |j| [j.name  + j.brand.name  + j.lot.number, j.id]}
            %p.text-right
              = link_to my_page_jeans_path, class: "link text-decoration-none" do
                Add New Jeans ->
            = f.text_field :tag_name, :placeholder => "Insert space when you add a hushtag yo your post!!"
            = f.submit
      %h2.mt-5
        View Posts
      - @posts.each do |post|
        - comment = post.comments.build
        - comment_reply = post.comments.build
        - comments = Comment.includes(:user).where(post_id: post.id).order(created_at: :desc)
        = render 'posts/posts', {post: post, comment: comment, comment_reply: comment_reply, comments: comments }
    .col-3

app/views/posts/new.html.haml
.container-fluid
  .row
    = render 'layouts/sidebar'
    .col-4
      %h2
        Post Your Jeans
      = bootstrap_form_with(current_user, Post.new) do |p|

app/views/posts/others.html.haml
.container-fluid
  .row
    - if user_signed_in?
      = render 'layouts/sidebar'
      .col-9
        .d-flex
          %i.far.fa-hand-point-left.pt-5.pl-5.text-success
          %h1.p-5
            Click Your Favorite Jeans!!
        .flex-wrap.slick_logged_in
          - @posts.each do |post|
            = link_to post_path(post), class: "text-decoration-none" do
              = image_tag post.image.url, class: "other-jeans-image mt-3 mb-3"
      .col-3
      .col-9
        .d-flex
          %i.fas.fa-trophy.pt-5.pl-5.text-warning.fa-trophy_icon
          %h1.p-5
            This weeks winners
            %span
              %h3
                (Last 7 days)
        .d-flex
          - @winners.each do |winner|
            .d-flex.flex-column.p-3
              %p
                %i.fas.fa-crown.text-warning
                = winner.award_id
              - jeans =  Jeans.find_by(id: winner.jeans_id)
              = link_to user_jeans_index_path(user_id: jeans.user_id), class: "text-decoration-none" do
                = image_tag jeans.jeans_image.url, class: "award-jeans-image_logged_in mb-3 rounded"

    - else
      .col-12
        .d-flex
          %i.far.fa-hand-point-left.pt-5.pl-5.text-success
          %h1.p-5
            Click Your Favorite Jeans!!
        .text-center.slick
          - @posts.each do |post|
            = link_to post_path(post), class: "text-decoration-none" do
              = image_tag post.image.url, class: "other-jeans-image mt-3 mb-3"
      .col-12
        .d-flex
          %i.fas.fa-trophy.pt-5.text-warning.fa-trophy_icon
          %h1.p-5
            This weeks winners
            %span
              %h3
                (Last 7 days)
        .d-flex
          - @winners.each do |winner|
            .d-flex.flex-column.p-3
              %h5
                %i.fas.fa-crown.text-warning
                = winner.award_id
              - jeans =  Jeans.find_by(id: winner.jeans_id)
              = link_to user_jeans_index_path(user_id: jeans.user_id), class: "text-decoration-none" do
                = image_tag jeans.jeans_image.url, class: "award-jeans-image mt-3 mb-3 rounded"

app/views/posts/show.html.haml
.container-fluid
  .row
    = render 'layouts/sidebar'
    .col-6.mx-auto
      = link_to user_path(@post.user, anchor: "flash_#{@post.id}"), class: "view_flash h4" do
        View this Jeans Posts ->
      .row
        .col-10.pr-0
          .card.mb-4.mt-5
            .bd-placeholder-img.card-img-top
              = image_tag @post.image.url, class: "card-image"
            .card-body
              - post_jeans = Jeans.find_by(id: @post.jeans_id)
              .d-flex
                = link_to user_path(@post.user) do
                  = image_tag @post.user.image.url, size: "50x50", class: "rounded-circle"
                .flex-column.ml-3
                  %strong
                    #{post_jeans.name}
                  %p.small
                    #{post_jeans.brand.name} #{post_jeans.lot.number} #{post_jeans.year.date_of_birth}
              %p.card-text
                = @post.body
              %p.text-right.small
                = @post.created_at.strftime("%Y-%m-%d %H:%M")
              .d-flex
                - @post.tags.each do |tag|
                  %p.card.rounded-pill.p-2.mr-2.small
                    = link_to tag_path(tag), class: "link edit-icon" do
                      = tag.tag_name
              .d-flex.icons
                -if post_jeans.is_nominated_by?(post_jeans, current_user)
                  .position-relative.mr-3
                    %i.fas.fa-check-circle.mr-4.trophy_complete{onClick: "click_trophy_complete()"}
                - else
                  .position-relative.mr-3
                    %i.fas.fa-trophy.text-warning.mr-4.trophy_icon{onClick: "click_trophy_icon(this)", id: "#{@post.id}"}
                .div{id: "post_#{@post.id}"}
                  .favorite_btn
                    = render "favorites/favorite_btn", post: @post
                .div{id: "relationship_#{@post.id}"}
                  .relationship_btn
                    = render "relationships/relationship_btn", post: @post
                .ml-5
                  = social_share_button_tag(@post.body)
            .nominate_form.ml-3.mb-3.mr-3.pt-3.border-top{id: "nominate_form_#{@post.id}"}
              = bootstrap_form_with url: nominee_maps_path, local: true do |f|
                .mb-2
                  Nominate This Jeans to...
                .d-flex
                  = f.select :nominee_id, NomineeMap.nominee_ids.keys, hide_label: true
                  = f.hidden_field :jeans_id, value: @post.jeans_id
                  = f.hidden_field :user_id, value: current_user.id
                = f.submit 'Vote!', class: "btn btn-primary"
                .nominate_close_button.btn.btn-dark{onclick: "close_trophy_icon(this)", id: "#{@post.id}"}
                  Close
            .comments_index
              .div{id: "comments_and_form_#{@post.id}"}
                = render "comments/index", {comment: @comment, comments: @comments, comment_reply: @comment_reply, post: @post}
        -if @difference_date < 10
          .col-2.first_step.mb-4.mt-5.border-right.border-top
            %p.strong.h4.text-white.pt-3
              Day
              = @difference_date
        - elsif @difference_date > 10
          .col-2.second_step.mb-4.mt-5.border-right.border-top
            %p.strong.h4.text-white.pt-3
              Day
              = @difference_date
        -elsif @difference_date > 60
          .col-2.third_step.mb-4.mt-5.border-right.border-top
            %p.strong.h4.text-white.pt-3
              Day
              = @difference_date

    .col-3

app/views/posts/timeline.html.haml
.container-fluid
  .row
    = render 'layouts/sidebar'
    .col-6.mx-auto
      %h2
        Timeline
      - @posts.each do |post|
        - comment = post.comments.build
        - comment_reply = post.comments.build
        - comments = Comment.includes(:user).where(post_id: post.id).order(created_at: :desc)
        = render 'posts/posts', {post: post, comment: comment, comment_reply: comment_reply, comments: comments }

    .col-3