config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :brands, only: :create
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'others' => 'posts#others'
  resources :nominees do
    get 'posts', to: 'posts#search'
  end
  resources :users do
    resources :jeans
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  get 'my_page' => 'users#my_page'
  get 'my_page/edit' => 'users#edit'
  get 'my_page/jeans' => 'jeans#index'
  get 'my_page/jeans/:id' => 'jeans#show', as: 'my_jeans'
  get 'my_page/timeline' => 'posts#timeline', as: 'timeline'
  get 'this_week', to: 'nominees#this_week'
  get 'last_weeks_winner', to: 'nominees#last_weeks_winner'
  resources :tags do
    get 'posts', to: 'posts#search'
  end
  resources :nominee_maps, only: [:create, :destroy]

end

app/models/award.rb
class Award < ApplicationRecord

  has_many :award_maps, dependent: :destroy, foreign_key: 'award_id'
  has_many :jeans, through: :award_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/award_map.rb
class AwardMap < ApplicationRecord

  belongs_to :jeans, optional: true
  belongs_to :award, optional: true

  enum award_id: { "Best Faded": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :lots
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
  belongs_to :parent,  class_name: "Comment", optional: true
  has_many   :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/jeans.rb
class Jeans < ApplicationRecord

  belongs_to :lot, optional: true
  belongs_to :brand, optional: true
  belongs_to :year, optional: true
  belongs_to :user, optional: true
  has_many :posts
  has_many :nominee_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :nominees, through: :nominee_maps
  has_many :award_maps, dependent: :destroy, foreign_key: 'jeans_id'
  has_many :awards, through: :award_maps

  mount_uploader :jeans_image, JeansUploader

  def is_nominated_by?(jeans, user)
    jeans.nominee_maps.find_by(user_id: user.id)
  end
end

app/models/lot.rb
class Lot < ApplicationRecord
  belongs_to :brand, optional: true
  has_many :years
end

app/models/nominee.rb
class Nominee < ApplicationRecord

  has_many :nominee_maps, dependent: :destroy, foreign_key: 'nominee_id'
  has_many :jeans, through: :nominee_maps

  enum name: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5}  # whisker ポケット下からモモの上まで , shevron モモから下の部分
end

app/models/nominee_map.rb
class NomineeMap < ApplicationRecord

  belongs_to :nominee,  optional: true
  belongs_to :jeans,  optional: true

  enum nominee_id: { "Best Faded Award": 1, "Best Fashionable": 2, "Best Whisker": 3, "Best Shevron": 4, "Best 501": 5 }

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :jean, optional: true
  belongs_to :user, optional: true


  mount_uploader :image, PostUploader

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags # 現在取得した@postに存在するタグから、送信されてきたタグを除いたタグをold_tagsとする。
    new_tags = sent_tags - current_tags # 送信されてきたタグ(sent_tag)から、現在存在するタグを除いたタグをnew_tagsとする。

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new) # tag_nameが存在していなければ、新たにレコード追加、既に存在する場合は既存のレコードを取得
      self.tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :post, optional: true

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jeans, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  mount_uploader :image, ImageUploader


  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :lot, optional: true
end

app/helpers/jeans_helper.rb
module JeansHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%header.mb-5
  %nav.navbar.navbar-expand-lg.navbar-light.p-4
    .flex-column
      = link_to others_path, class: "text-white text-decoration-none" do
        %h1.pb-0
          Jeans
        %small raise your jeans, live with jeans
    %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
    #navbarNavDropdown.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          %li.nav-item
            = link_to "LOOK NOMINEES", this_week_path, class: 'text-white nav-link'
          %li.nav-item
            = link_to 'MY PAGE', my_page_path, class: 'text-white nav-link'
          %li.nav-item
            = link_to "POST JEANS", posts_path, class: 'text-white nav-link'
          %li.nav-item
            = link_to "TIMELINE", timeline_path, class: 'text-white nav-link'
          %li.nav-item
            = link_to "LOG OUT", destroy_user_session_path, method: :delete, class: 'text-white nav-link'
        - else
          %li.nav-item
            = link_to "SINE UP", new_user_registration_path, class: 'text-white nav-link'
          %li.nav-item
            = link_to "LOG IN", new_user_session_path, class: 'text-white nav-link'

app/views/layouts/_sidebar.html.haml
.col-3.mt-5
  %h3.mt-5
    = link_to others_path, class: "text-decoration-none text-dark" do
      All Posts
  %h3.mt-5
    = link_to posts_path, class: "text-decoration-none text-dark" do
      Your Posts
  %h3.mt-5
    = link_to my_page_path, class: "text-decoration-none text-dark" do
      Awards

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Denim
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    %link{href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel: "stylesheet", type: "text/css"}/
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href:"https://fonts.googleapis.com/css2?family=Ultra&display=swap", rel: "stylesheet"}
    %script{src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", type: "text/javascript"}
    %link{rel:"stylesheet", href:"https://unpkg.com/charts.css/dist/charts.min.css"}

  %body
    .bg-mask
      = render 'layouts/header'
      = yield